Ignore decode errors
If there are unconforming entries in the input file the python open function can´t parse the input and throws an exception as the default error handling is set to 'strict'.
Setting it to 'ignore' skips these characters and lets the exectuion continue.

Error seen in our Monitoring:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 2443: invalid start byte